name: Ubuntu Clang Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libxcb-cursor0

    - name: Download LLVM
      run: |
        # Using the Linux x86_64 Ubuntu build for LLVM 21.1.8
        URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/LLVM-21.1.8-Linux-X64.tar.xz"
        curl -L "$URL" -o llvm.tar.xz

    - name: Extract LLVM
      run: |
        mkdir -p llvm-dist
        tar -xf llvm.tar.xz -C llvm-dist --strip-components 1

    - name: Setup Path
      run: |
        # Add LLVM to GITHUB_PATH
        echo "$(pwd)/llvm-dist/bin" >> $GITHUB_PATH

        cd test_program
        mkdir build

    - name: Test Case 0
      if: always()
      run: |
        root=$(pwd)
        cd test_program/build
        cmake -S .. -B . \
          -G "Ninja" \
          -DCMAKE_C_COMPILER="$root/llvm-dist/bin/clang" \
          -DCMAKE_CXX_COMPILER="$root/llvm-dist/bin/clang++" \
          -DCMAKE_INSTALL_PREFIX:PATH="$root/install" \
          -DCMAKE_CXX_SCAN_FOR_MODULES=1 \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
          -DCMAKE_BUILD_TYPE=Release \
          -DTEST_CASE=0
        cmake --build .
        cmake --install .
        $root/install/test_program

    - name: Test Case 1
      if: always()
      run: |
        root=$(pwd)
        cd test_program/build
        cmake -S .. -B . \
          -G "Ninja" \
          -DCMAKE_C_COMPILER="$root/llvm-dist/bin/clang" \
          -DCMAKE_CXX_COMPILER="$root/llvm-dist/bin/clang++" \
          -DCMAKE_INSTALL_PREFIX:PATH="$root/install" \
          -DCMAKE_CXX_SCAN_FOR_MODULES=1 \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
          -DCMAKE_BUILD_TYPE=Release \
          -DTEST_CASE=1
        cmake --build .
        cmake --install .
        $root/install/test_program

    - name: Test Case 2
      if: always()
      run: |
        root=$(pwd)
        cd test_program/build
        cmake -S .. -B . \
          -G "Ninja" \
          -DCMAKE_C_COMPILER="$root/llvm-dist/bin/clang" \
          -DCMAKE_CXX_COMPILER="$root/llvm-dist/bin/clang++" \
          -DCMAKE_INSTALL_PREFIX:PATH="$root/install" \
          -DCMAKE_CXX_SCAN_FOR_MODULES=1 \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
          -DCMAKE_BUILD_TYPE=Release \
          -DTEST_CASE=2
        cmake --build .
        cmake --install .
        $root/install/test_program

    - name: Test Case 3
      if: always()
      run: |
        root=$(pwd)
        cd test_program/build
        cmake -S .. -B . \
          -G "Ninja" \
          -DCMAKE_C_COMPILER="$root/llvm-dist/bin/clang" \
          -DCMAKE_CXX_COMPILER="$root/llvm-dist/bin/clang++" \
          -DCMAKE_INSTALL_PREFIX:PATH="$root/install" \
          -DCMAKE_CXX_SCAN_FOR_MODULES=1 \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
          -DCMAKE_BUILD_TYPE=Release \
          -DTEST_CASE=3
        cmake --build .
        cmake --install .
        $root/install/test_program
