name: Ubuntu Clang Build

on:
  push:
    branches: [ "function-address-mismatch" ]
  pull_request:
    branches: [ "function-address-mismatch" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libxcb-cursor0

    - name: Download LLVM
      run: |
        URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/LLVM-21.1.8-Linux-X64.tar.xz"
        curl -L "$URL" -o llvm.tar.xz

    - name: Extract LLVM
      run: |
        mkdir -p llvm-dist
        tar -xf llvm.tar.xz -C llvm-dist --strip-components 1

    - name: Setup Path
      run: |
        echo "$(pwd)/llvm-dist/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        cd test_program
        clang++ -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++ -std=c++20 -fPIC test_module/test_module.pcm -c -o test_module/test_module.o
        clang++ -shared -o test_module/libtest_module.so test_module/test_module.o
        clang++ -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o
        clang++ main.o test_module/libtest_module.so -o app

    - name: Run
      run: |
        cd test_program
        cp test_module/libtest_module.so ./
        ./app
