name: Windows MSVC Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create Build Directory
      run: |
        mkdir -p test_program/build
        mkdir -p install

    - name: Test Case 0
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -G "Ninja" `
          -DCMAKE_INSTALL_PREFIX="$root/install" `
          -DCMAKE_CXX_SCAN_FOR_MODULES=1 `
          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 `
          -DCMAKE_BUILD_TYPE=Release `
          -DTEST_CASE=0
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"

    - name: Test Case 1
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -DTEST_CASE=1
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"

    - name: Test Case 2
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -DTEST_CASE=2
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"

    - name: Test Case 3
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -DTEST_CASE=3
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"

    - name: Test Case 4
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -DTEST_CASE=4
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"

    - name: Test Case 5
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -DTEST_CASE=5
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"

    - name: Test Case 6
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -DTEST_CASE=6
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"

    - name: Test Case 7
      if: always()
      run: |
        $root = Get-Location
        cmake -S test_program -B test_program/build `
          -DTEST_CASE=7
        cmake --build test_program/build
        cmake --install test_program/build
        & "$root/install/test_program.exe"
