name: Windows Clang Build

on:
  push:
    branches: [ "function-address-mismatch" ]
  pull_request:
    branches: [ "function-address-mismatch" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Download LLVM
      run: |
        URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/clang+llvm-21.1.8-x86_64-pc-windows-msvc.tar.xz"
        curl -L "$URL" -o llvm.tar.xz

    - name: Extract LLVM
      run: |
        mkdir -p llvm-dist
        tar -xf llvm.tar.xz -C llvm-dist --strip-components 1

    - name: Setup Path
      run: |
        LLVM_BIN_UNIX="$(pwd)/llvm-dist/bin"
        LLVM_BIN_WIN=$(cygpath -w "$LLVM_BIN_UNIX")
        
        echo "$LLVM_BIN_WIN" >> $GITHUB_PATH

    - name: Output Debug Files
      if: always()
      run: |
        cd test_program
        mkdir debug_files
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm -### 2> ./debug_files/clang_cmd_test_module.txt
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm

        clang++.exe -std=c++20 -S -emit-llvm test_module/test_module.pcm -o ./debug_files/test_module.ll

        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -fuse-ld=lld -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=0

        # Debug Output
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=5 -### 2> ./debug_files/clang_cmd_main.txt
        clang++.exe -std=c++20 -fprebuilt-module-path=test_module -DTEST_CASE=0 -S -emit-llvm main.cpp -o ./debug_files/main_case0.ll
        clang++.exe -std=c++20 -fprebuilt-module-path=test_module -DTEST_CASE=1 -S -emit-llvm main.cpp -o ./debug_files/main_case1.ll
        clang++.exe -std=c++20 -fprebuilt-module-path=test_module -DTEST_CASE=2 -S -emit-llvm main.cpp -o ./debug_files/main_case2.ll
        clang++.exe -std=c++20 -fprebuilt-module-path=test_module -DTEST_CASE=3 -S -emit-llvm main.cpp -o ./debug_files/main_case3.ll
        clang++.exe -std=c++20 -fprebuilt-module-path=test_module -DTEST_CASE=4 -S -emit-llvm main.cpp -o ./debug_files/main_case4.ll
        clang++.exe -std=c++20 -fprebuilt-module-path=test_module -DTEST_CASE=5 -S -emit-llvm main.cpp -o ./debug_files/main_case5.ll
        clang++.exe -std=c++20 -fprebuilt-module-path=test_module -DTEST_CASE=6 -S -emit-llvm main.cpp -o ./debug_files/main_case6.ll

    - name: Build
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -fuse-ld=lld -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib

        mkdir debug_files
        cp ./test_module/test_module.lib debug_files/
        cp ./test_module/test_module.dll debug_files/

        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o
        clang++.exe -fuse-ld=lld main.o test_module/test_module.lib -o app.exe

    - name: Run
      run: |
        cp test_module/test_module.dll test_module/
        ./app.exe

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-files
        path: test_program/debug_files/**
