name: Windows Clang Build (Bash)

on:
  push:
    branches: [ "undefined-symbol" ]
  pull_request:
    branches: [ "undefined-symbol" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Download LLVM
      run: |
        URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/clang+llvm-21.1.8-x86_64-pc-windows-msvc.tar.xz"
        curl -L "$URL" -o llvm.tar.xz

    - name: Extract LLVM
      run: |
        mkdir -p llvm-dist
        tar -xf llvm.tar.xz -C llvm-dist --strip-components 1

    - name: Setup Path
      run: |
        LLVM_BIN_UNIX="$(pwd)/llvm-dist/bin"
        LLVM_BIN_WIN=$(cygpath -w "$LLVM_BIN_UNIX")
        
        echo "$LLVM_BIN_WIN" >> $GITHUB_PATH

        cd test_program
        mkdir build

    - name: Test Case 0
      if: always()
      run: |
        root=$(pwd)
        cd test_program
        cmd.exe /c build.bat 0

    - name: Test Case 1
      if: always()
      run: |
        root=$(pwd)
        cd test_program
        cmd.exe /c build.bat 1
