name: Windows Clang Build (Bash)

on:
  push:
    branches: [ "undefined-symbol-no-cmake" ]
  pull_request:
    branches: [ "undefined-symbol-no-cmake" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Download LLVM
      run: |
        URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/clang+llvm-21.1.8-x86_64-pc-windows-msvc.tar.xz"
        curl -L "$URL" -o llvm.tar.xz

    - name: Extract LLVM
      run: |
        mkdir -p llvm-dist
        tar -xf llvm.tar.xz -C llvm-dist --strip-components 1

    - name: Setup Path
      run: |
        LLVM_BIN_UNIX="$(pwd)/llvm-dist/bin"
        LLVM_BIN_WIN=$(cygpath -w "$LLVM_BIN_UNIX")
        
        echo "$LLVM_BIN_WIN" >> $GITHUB_PATH

    - name: Test Case 0
      if: always()
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=0
        clang++.exe main.o test_module/test_module.lib -o app.exe
        ./app.exe

    - name: Test Case 1
      if: always()
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=1
        clang++.exe main.o test_module/test_module.lib -o app.exe
        ./app.exe

    - name: Test Case 2
      if: always()
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=2
        clang++.exe main.o test_module/test_module.lib -o app.exe
        ./app.exe

    - name: Test Case 3
      if: always()
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=3
        clang++.exe main.o test_module/test_module.lib -o app.exe
        ./app.exe

    - name: Test Case 4
      if: always()
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=4
        clang++.exe main.o test_module/test_module.lib -o app.exe
        ./app.exe

    - name: Test Case 5
      if: always()
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=5
        clang++.exe main.o test_module/test_module.lib -o app.exe
        ./app.exe

    - name: Test Case 6
      if: always()
      run: |
        cd test_program
        clang++.exe -std=c++20 test_module/test_module.cppm --precompile -o test_module/test_module.pcm
        clang++.exe -std=c++20 test_module/test_module.pcm -c -o test_module/test_module.o
        clang++.exe -shared -o test_module/test_module.dll test_module/test_module.o -Wl,/IMPLIB:test_module/test_module.lib
        clang++.exe -std=c++20 main.cpp -fprebuilt-module-path=test_module -c -o main.o -DTEST_CASE=6
        clang++.exe main.o test_module/test_module.lib -o app.exe
        ./app.exe
